DELETE FROM arch_process_instance A WHERE exists (
SELECT rootprocessinstanceid
FROM arch_process_instance B
WHERE B.ROOTPROCESSINSTANCEID = B.SOURCEOBJECTID
AND A.ROOTPROCESSINSTANCEID = B.ROOTPROCESSINSTANCEID
AND PROCESSDEFINITIONID = ?
and (STATEID = 6 OR STATEID = 3 OR STATEID = 4)
AND ENDDATE <= ?) AND tenantId = ?
;