name: Build & test Bonita Purge Tool

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: distribution
        path: build/distributions/bonita-purge-tool.zip
    - name: Archive test results
      uses: actions/upload-artifact@v1
      with:
        name: unit tests
        path: build/reports/tests/test/
